### ISSUE TITLE
batchnorm parameters

### ISSUE THREAD

**Issue by neptune4year** [fxmeng/filter-grafting#12]
I would like to know do you use bn in grafting training?
If so, how do you grafting bn parameters, the same as weights?

**Comment by fxmeng** [comment]
the coefficient of bn layer consistent with the conv parameters in the previous layer

**Comment by neptune4year** [comment]
> the coefficient of bn layer consistent with the conv parameters in the previous layer

Sorry, I didn't get it.
May I ask you to describe the exactly actions on bn coefficients during grafting?
Thanks very much!

**Comment by fxmeng** [comment]
![image](https://user-images.githubusercontent.com/60565778/79550067-71402600-80ca-11ea-9779-396f73da4b47.png)

**Comment by fxmeng** [comment]
The value of  w will only change when it encounters the conv layer

**Comment by neptune4year** [comment]
> The value of w will only change when it encounters the conv layer

Thanks so much for your reply.
I got it know.

Beat regards!
