### ISSUE TITLE
您好，我有几个关于grafting.py代码的问题想请教您

### ISSUE THREAD

**Issue by linklist2** [fxmeng/filter-grafting#18]
![image](https://user-images.githubusercontent.com/46252413/129301908-5ecdc1d2-10c8-451a-845a-01135dd434b3.png)
您好，针对这段代码我有几个问题想请教您：
问题1：graft操作对卷积层的权重和偏置以及后面的BN层都进行了处理了吗？
问题2：对于vgg16的情况，key是features.0.weight,  features.1.bias这样的形式，该如何修改才能使这段代码适用于vgg16呢？
![image](https://user-images.githubusercontent.com/46252413/129302535-c5cd5947-ddb6-409f-961c-6c39c9925e47.png)

**Comment by fxmeng** [comment]
当判断为卷积weight的时候，w会更新，其他情况使用之前的w值，因此所有的层都会进行操作。如果key的名字不同，只要找到conv的层就可以，例如判断矩阵shape长度是否为4。

**Comment by linklist2** [comment]
> 当判断为卷积weight的时候，w会更新，其他情况使用之前的w值，因此所有的层都会进行操作。如果key的名字不同，只要找到conv的层就可以，例如判断矩阵shape长度是否为4。

多谢作者
