### ISSUE TITLE
Ambiguous value for fuse-weight?

### ISSUE THREAD

**Issue by hiyijian** [fxmeng/filter-grafting#3]
```
    for i,(key,u) in enumerate(net.state_dict().items()):
        if 'conv' in key:
            w=round(0.4*(np.arctan(500*((float(entropy(u).cpu())-float(entropy(checkpoint[key]).cpu())))))/np.pi+1/2,2)
        model[key]=u*w+checkpoint[key]*(1-w)
```
For layeres are not "conv", such as "BN", what value of "w"  sholud be? It seemes that they are determinted by the previous layer, typically are pre "conv"?

**Comment by fxmeng** [comment]
Thanks for your question,
You are right，the weighted average coefficient of the BN layer and the FC layer are determined by the convolutional layer of the previous layer. Since the parameters of the BN layer and the convolution layer are related, so is the FC layer.
