### ISSUE TITLE
作者你好，请问一下您，直接运行grafting.py，无法直接训练  数据集是CIFAR10

### ISSUE THREAD

**Issue by a1037441813** [fxmeng/filter-grafting#9]
直接运行grafting.py  无法一直训练 

训练只会到 epoch 0 ， 然后暂停 ，，，显示是一直停留在time.sleep(10)这个语句。。。
请问下作者
正常的训练步骤是怎样的，，，我的问题出在哪里。。。谢谢

**Comment by fxmeng** [comment]
你好,
grafting需要多个程序配合着训练,当使用两个模型grafting时,需要跑两个程序,设置num=2,其中一个程序设置i=1,另一个程序设置i=2.这样每个程序读取前一个程序的模型,才能跑起来.

**Comment by junleiz** [comment]
应该是你模型路径不对
